apps/index/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [path("", views.index, name="index")]

apps/iss/urls.py
from django.urls import path
from . import views

app_name = "iss"

urlpatterns = [path("", views.index, name="index")]

apps/polls/urls.py
from django.urls import path
from . import views

urlpatterns = [path("", views.index, name="index")]

apps/words/urls.py
from django.urls import path
from . import views

app_name = "words"

urlpatterns = [path("", views.index, name="index")]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("apps.index.urls")),
    path("polls/", include("apps.polls.urls")),
    path("iss/", include("apps.iss.urls")),
    path("words/", include("apps.words.urls")),
    path("admin/", admin.site.urls),
]

apps/words/models.py
from django.db import models

# Create your models here.

apps/index/views.py
from django.shortcuts import render
from django.template import loader
from django.contrib.staticfiles import finders
import random
import pandas

def get_yojijukugo():
    csv_file_path = finders.find("index/yojijukugo.csv")
    csv_data = pandas.read_csv(csv_file_path)
    dict_data = csv_data.to_dict(orient="records")
    return random.choice(dict_data)



# Create your views here.
def index(request):
    context = {
        "fc": get_yojijukugo(),
    }
    return render(request, "index/index.html", context)

apps/iss/views.py
from django.shortcuts import render
import requests


# Create your views here.
def index(request):
    response = requests.get("http://api.open-notify.org/iss-now.json")
    response_json = response.json()
    context = {
        "longitude": response_json["iss_position"]["longitude"],
        "latitude": response_json["iss_position"]["latitude"],
    }
    return render(request, "iss/index.html", context)

apps/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

apps/words/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    context = {}
    return render(request, "words/index.html", context)

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Pretty Much Rainbow</title>
    <!-- bootstrap -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <!-- web font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Ops+One&display=swap" rel="stylesheet">
    <!-- common css -->
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
    <!-- custom css -->
    {% block custom_css %}
    {% endblock custom_css %}
  </head>
  <body>
    <div class="container">
      <div>
        <h1 class="title"><a href="{% url 'index:index' %}">Pretty Much Rainbow</a></h1>
      </div>
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>

templates/index/index.html
{% extends 'base.html' %}

{% block custom_css %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Reggae+One&display=swap" rel="stylesheet">
{% endblock custom_css %}

{% block content %}
  <!-- Random -->
  <div class="card mt-3">
    <div class="card-header menu_font">
      らんだむ四字熟語くん 漢検1級ver
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>
          <ruby>
            <span class="fw-bold">{{ fc.Word }}</span>
            <rt>{{ fc.Yomi }}</rt>
          </ruby>
        </p>
        <footer class="blockquote-footer">{{ fc.Meaning }}</footer>
      </blockquote>
    </div>
  </div>

  <!-- Menu -->
  <div class="card-group mt-3">
    <!-- ISS Location -->
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title menu_font">Where Is ISS?</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">
          <span class="badge text-bg-info">Information</span>
          <span class="badge text-bg-secondary">Simple</span>
          <span class="badge text-bg-success">Hobby</span>
        </h6>
        <p class="card-text">現在の国際宇宙ステーション（ISS）の位置をGoogle Map上に表示します。</p>
        <a href="{% url 'iss:index' %}"> &gt;&gt; Go</a>
      </div>
    </div>
    <!-- BookWord Estimator -->
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title menu_font">BookWord Estimator</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">
          <span class="badge text-bg-secondary">Simple</span>
          <span class="badge text-bg-success">Hobby</span>
        </h6>
        <p class="card-text">洋書の語数を推定します。</p>
        <a href="{% url 'words:index' %}"> &gt;&gt; Go</a>
      </div>
    </div>
  </div>
{% endblock content %}

templates/iss/index.html
{% extends 'base.html' %}

{% block custom_css %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Reggae+One&display=swap" rel="stylesheet">
{% endblock custom_css %}

{% block content %}
  <div class="mt-3">
    <h2 class="menu_font">Where Is ISS?</h2>
  </div>
  <div class="mt-3">
    <iframe src="http://maps.google.co.jp/maps?q={{ latitude }},{{ longitude }}&output=embed&t=m&z=2&hl=ja" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
  </div>
  <div>
    <a href="{% url 'index:index' %}">Back to Index</a>
  </div>
{% endblock content %}

templates/words/index.html
{% extends 'base.html' %}

{% block custom_css %}
{% endblock custom_css %}

{% block content %}
<div class="mt-3">
  <h2 class="menu_font">BookWord Estimator</h2>
</div>
<div class="mt-3 mb-3">
  <p>1行に含まれる語数を入力（ランダムに選択）</p>
  <div class="container words">
    <div class="row">
      <div class="col">
        <input type="text" class="d-inline form-control">
      </div>
      <div class="col">
        <input type="text" class="d-inline form-control">
      </div>
      <div class="col">
        <input type="text" class="d-inline form-control">
      </div>
      <div class="col">
        <input type="text" class="d-inline form-control">
      </div>
      <div class="col">
        <input type="text" class="d-inline form-control">
      </div>
    </div>
  </div>
  <p class="mt-3">1ページ当たりの行数を入力</p>
  <div class="container line">
    <div class="row">
      <div class="col">
        <input type="text" class="d-inline form-control">
      </div>
    </div>
  </div>
  <p class="mt-3">ページ数を入力</p>
  <div class="container page">
    <div class="row">
      <div class="col">
        <input type="text" class="d-inline form-control">
      </div>
    </div>
  </div>
  <p class="mt-3">係数</p>
  <div class="container rate">
    <div class="row">
      <div class="col">
        <input type="text" class="d-inline form-control" value="0.9">
      </div>
    </div>
  </div>
  <p class="mt-3">推定語数</p>
  <div class="card text-center">
    <div class="card-body">
      <p class="card-text fs-1">12,900</p>
      <a href="#" class="btn btn-primary">Copy</a>
    </div>
  </div>
</div>
<div>
  <a href="{% url 'index:index' %}">Back to Index</a>
</div>
{% endblock content %}